# Generated by Django 3.0.6 on 2020-05-16 16:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_url', models.URLField()),
                ('vk_public_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('source', models.URLField(unique=True)),
                ('publish_date', models.DateField()),
                ('cluster_difference', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None)),
                ('title_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None)),
                ('text_sentences', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('text_sentence_embeddings', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), default=[], size=None)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Cluster')),
            ],
        ),
    ]
